# This file describes a blueprint for use in Crafter Studio

# The version of this type of this file
descriptorVersion: 1

# Describe the blueprint
blueprint:
  id: org.craftercms.blueprint.event
  name: "Crafter CMS Blueprint: Event"
  tags: blueprint,event
  version:
    major: 2
    minor: 0
    patch: 0
  description: |
    "Crafter CMS Blueprint: Event"
  media:
    screenshots:
      - screenshot:
          title: Home page
          description: Screenshot of the home page
          url: ""
      - screenshot:
          title: Contact Section
          description: Screenshot of the contact section of the page
          url: ""
    developer:
      company:
        name: Rivet Logic
        email: support@rivetlogic.com
        url: https://rivetlogic.com
  build:
    id: c3d2a5444e6a24b5e0481d6ba87901d0b02716c8
    date: 2019-03-18T00:00:00Z
  license:
    name: GNU
    url: https://opensource.org/licenses/GPL-3.0
  craftercmsVersionsSupported:
    - version: 3.1.0
  searchEngine: Elasticsearch